### ISSUE TITLE
Add test coverage

### ISSUE THREAD

**Issue by ghost** [vivo-project/Vitro-angular#3]
Should provide npm script to run test coverage and afford sending coverage to external service such as [codecov](https://about.codecov.io/) or [coveralls](https://coveralls.io/)

**Comment by chenejac** [comment]
CodeCov looks as a little bit more popular solution, and I didn't hear for some significant advantage of Coveralls over CodeCov, therefore I am for CodeCov. Other opinions? CodeCov is free in our case, right?
